# Generated by Django 3.0.6 on 2020-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200611_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('1', 'CRITICAL'), ('2', 'DEBUG'), ('3', 'ERROR'), ('4', 'WARNING'), ('5', 'INFO')], max_length=20),
        ),
    ]
