# Generated by Django 3.0.6 on 2020-06-12 21:22

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200612_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.TextField(max_length=39, validators=[django.core.validators.validate_ipv4_address], verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='env',
            field=models.CharField(max_length=20, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=5, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='event',
            name='arquivado',
            field=models.BooleanField(verbose_name='Arquivado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Último login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Senha'),
        ),
    ]
