# Generated by Django 3.0.6 on 2020-06-15 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200612_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('1', 'CRITICAL'), ('2', 'DEBUG'), ('3', 'ERROR'), ('4', 'WARNING'), ('5', 'INFO')], max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator], verbose_name='Senha'),
        ),
    ]
